### ISSUE TITLE
[PkgEval] Lumira may have a testing issue on Julia 0.4 (2014-08-16)

### ISSUE THREAD

**Issue by IainNZ** [sbcd90/Lumira.jl#1]
[PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) is a script that runs nightly. It attempts to load all Julia packages and run their tests (if available) on both the stable version of Julia (0.3) and the nightly build of the unstable version (0.4). The results of this script are used to generate a [package listing](http://pkg.julialang.org/) enhanced with testing results.
#### On Julia 0.4
- On **2014-08-16** the testing status was `N/A - new package.`
- On **2014-08-16** the testing status changed to `Tests fail, but package loads.`

`Tests fail, but package loads.` means that PackageEvaluator found the tests for your package, executed them, and they didn't pass. However, trying to load your package with `using` worked.

_This issue was filed because your testing status became worse. No additional issues will be filed if your package remains in this state, and no issue will be filed if it improves. If you'd like to opt-out of these status-change messages, reply to this message saying you'd like to and @IainNZ will add an exception. If you'd like to discuss [PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) please file an issue at the repository. For example, your package may be untestable on the test machine due to a dependency - an exception can be added._

_Test log_:

```
>>> 'Pkg.add("Lumira")' log
INFO: Installing ArrayViews v0.4.6
INFO: Installing Codecs v0.1.2
INFO: Installing Color v0.3.0
INFO: Installing Compose v0.3.6
INFO: Installing Contour v0.0.2
INFO: Installing DataArrays v0.2.0
INFO: Installing DataFrames v0.5.7
INFO: Installing DataStructures v0.3.1
INFO: Installing Datetime v0.1.6
INFO: Installing Distance v0.4.0
INFO: Installing Distributions v0.5.4
INFO: Installing FixedPointNumbers v0.0.1
INFO: Installing GZip v0.2.13
INFO: Installing Gadfly v0.3.6
INFO: Installing Hexagons v0.0.2
INFO: Installing ImmutableArrays v0.0.6
INFO: Installing Iterators v0.1.6
INFO: Installing JSON v0.3.7
INFO: Installing KernelDensity v0.0.2
INFO: Installing Loess v0.0.2
INFO: Installing Lumira v0.0.1
INFO: Installing PDMats v0.2.3
INFO: Installing Reexport v0.0.1
INFO: Installing SortingAlgorithms v0.0.1
INFO: Installing StatsBase v0.6.3
INFO: Building Datetime
INFO: Package database updated

>>> 'using Lumira' log

>>> test log
ERROR: LumiraGadfly not found
 in require at loading.jl:47
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
 in _start_3B_3500 at /home/idunning/julia04/usr/bin/../lib/julia/sys.so
while loading /home/idunning/pkgtest/.julia/v0.4/Lumira/test/runtests.jl, in expression starting on line 1


>>> end of log
```

**Comment by sbcd90** [comment]
Issue should be fixed in the next build...tagged version 0.0.2 should fix it...

**Comment by sbcd90** [comment]
Hello @IainNZ  can you please run the checks again...or is it possible to automate it, so that it runs everyday?

**Comment by IainNZ** [comment]
It is a fully automated system, it does run every day. You still haven't tagged version 0.0.2 in METADATA though: https://github.com/JuliaLang/METADATA.jl/tree/metadata-v2/Lumira

**Comment by sbcd90** [comment]
@IainNZ  Thanks for letting me know...can you please merge my pull request?
